---
swagger: "2.0"
info:
  description: "The Accounts Consent Management API manages accounts consents according\
    \ to the NEXT GEN PSD2 XS2A Specification"
  version: "1.0.0"
  title: "Accounts Consent Management API v1.0.0"
  contact:
    name: "WSO2"
    url: "http://wso2.com/solutions/financial/open-banking/"
    email: "openbankingdemo@wso2.com"
  license:
    name: "WSO2 Commercial License"
    url: "https://github.com/wso2/financial-open-banking/blob/master/LICENSE"
basePath: "/openbanking/stet/v1.4.0"
tags:
- name: "myresource"
schemes:
- "https"
